repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
      exclude: ^tests/TEST_DATA
    - id: check-added-large-files
    - id: check-yaml
    - id: check-toml
    - id: check-json

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: "ruff format ."
        language: python
        pass_filenames: false
        require_serial: true
      - id: mypy
        name: mypy
        entry: "mypy ."
        language: python
        pass_filenames: false
        require_serial: true
      - id: ruff
        name: ruff
        entry: "ruff check --fix ."
        language: python
        pass_filenames: false
        require_serial: true

